### ISSUE TITLE
About WikiAnn

### ISSUE THREAD

**Issue by zyq0000** [Mckysse/MSD#1]
Thanks for you excellent work. I am so interested in your work, and I have some questions about the WikiAnn dataset. I got the source dataset from this [link](https://www.dropbox.com/s/12h3qqog6q4bjve/panx_dataset.tar). After data statistics, I found that the number of entities in Chinese does not match the number mentioned in your paper. Could you provide me with the dataset used in your paper? Thanks for your kindness!

**Comment by Mckysse** [comment]
Thanks. As for the WikiAnn dataset, actually we use the version of balanced splits mentioned in XTREME benchmark for fair comparison. You could refer to the article "[Xtreme: A massively multilingual multi-task benchmark for evaluating cross-lingual generalisation](http://proceedings.mlr.press/v119/hu20b)" and the balanced Wikiann dataset from "[Massively multilingual transfer for NER](https://arxiv.org/abs/1902.00193)". Dataset and pre-processing code could be found in the link in the Xtreme paper.

**Comment by zyq0000** [comment]
Thanks for your reply. And I will check it again.
